### ISSUE TITLE
Unhandled Rejection (Error): Given action "ENIGMA_INITIALIZED", reducer "enigma" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

### ISSUE THREAD

**Issue by Rimay** [lauraweindorf/enigma-millionaires-problem#6]
Hello, I followed your instruction but the front-end demo encountered an error as below:

Unhandled Rejection (Error): Given action "ENIGMA_INITIALIZED", reducer "enigma" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
▶ 3 stack frames were collapsed.
App._callee$
src/components/App.js:38
  35 | // Initialize enigma-js client library (including web3)
  36 | const enigma = await getEnigmaInit();
  37 | // Create redux action to initialize set state variable containing enigma-js client library
> 38 | this.props.initializeEnigma(enigma);
     | ^  39 | // Initialize unlocked accounts
  40 | const accounts = await enigma.web3.eth.getAccounts();
  41 | // Create redux action to initialize set state variable containing unlocked accounts
View compiled
▶ 5 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

Does anyone know how to solve it?

By the way, is the front-end port number 3000?

**Comment by lauraweindorf** [comment]
Resolved here: https://forum.enigma.co/t/error-when-running-discovery-test-for-tutorial-millionaires-problem/1130/14

@Rimay's setup was running discovery on a separate server and needed to expose ports 3333 (for enigma's p2p network) and 9545 (local truffle network for testing), and accessing the dApp via port 3000 in his local environment on his laptop. Great help from @levackt in identifying the resolution!
